### ISSUE TITLE
Magnus Larsson kitap 2. edisyon

### ISSUE THREAD

**Issue by cybora** [uppnrise/acme-microservice-template#2]
Selamlar, Magnus Larsson'ın kitabını takip ettiğini gördüm yapmış olduğun commit sonrasında. 

Daha önceden bilgin var mı bilmiyorum ama kitabın 2. edisyonu önümüzdeki ay geliyor. Seninle paylaşmak istedim meraklı olduğun için ilgili repo adresini, henüz kodlar hazır değil gibi, Magnus ara ara gönderiyor. Bildiğin gibi ilk kitapta anlatılan bazı şeyler zaman içerisinde ya deprecated oldu ya yeni yöntemlere geçildi ( spring cloud stream kafka gibi yerlerde functional programming e geçilmesi gibi ) ya da farklı sebeplerden dolayı kodların spring bootun güncel versiyonlarında çalışabilmesi için yeni trickler gerekti.

Bu durumdan dolayı acaba yeni bir sürüm gelir mi yakında vs diye bakınırken şans eseri Packt'in reposunda rastladım yeni kitabın kodlarına. Packt'in web sitesinde de önümüzdeki ay kitabın çıkacağı bilgisi mevcut.

https://www.packtpub.com/product/microservices-with-spring-boot-and-spring-cloud-second-edition/9781801072977

https://github.com/PacktPublishing/Hands-On-Microservices-with-Spring-Boot-and-Spring-Cloud-2E

Kolay gelsin,

**Comment by uppnrise** [comment]
selam, kitabın 2. versiyonundan haberim var ama yeni bir repo olduğunu öğrendiğim iyi oldu. 

Bilgilendirme için teşekkürler.
